DROP TABLE IF EXISTS time_records CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;

CREATE TABLE tasks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       description TEXT,
                       status VARCHAR(50) NOT NULL
);

CREATE TABLE time_records (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              employee_id BIGINT NOT NULL,
                              task_id BIGINT NOT NULL,
                              start_time TIMESTAMP NOT NULL,
                              end_time TIMESTAMP NOT NULL,
                              description TEXT,
                              FOREIGN KEY (task_id) REFERENCES tasks(id)
);